"""
NeoGuard AI — LLM explanation engine.

Provider priority:
  1. Cache   — check llm_explanations table first (avoids all API calls)
  2. Gemini  — primary (Google AI Studio key from .env)
  3. Groq    — automatic fallback on ANY Gemini error: missing key, rate limit,
               quota exceeded, invalid key, network error, JSON parse failure.
               Uses Llama-3.3-70B-Versatile on the Groq free tier.
  4. Rule-based — final fallback when both LLMs are unavailable.
               Explicitly labelled NOT AI-generated in the UI.
"""

from __future__ import annotations

import hashlib
import json
import traceback
from datetime import datetime, timedelta, timezone
from typing import Any

import google.generativeai as genai
from groq import Groq

from config import get_settings
from db import get_supabase
from rag.retrieve import EvidenceChunkResult
from schemas import CitationItem, EvidenceChunkResponse, ExplanationResponse


# ── Disclaimers ───────────────────────────────────────────────────────────────

DISCLAIMER = (
    "This explanation is generated by AI and is provided for educational support only. "
    "Clinical decisions must be made by a qualified clinician based on the full clinical picture. "
    "NeoGuard AI does not replace clinical judgement."
)

RULE_BASED_DISCLAIMER = (
    "This is a rule-based summary — NOT AI-generated. "
    "No language model was used. Recommendations are derived deterministically from "
    "the EOSCAL score and active guideline protocol. "
    "Clinical decisions must be made by a qualified clinician."
)

_SOURCE_URLS: dict[str, str] = {
    "NICE":       "https://www.nice.org.uk/guidance/ng195",
    "NG195":      "https://www.nice.org.uk/guidance/ng195",
    "AAP":        "https://publications.aap.org/pediatrics/article/150/6/e2022057091/190641",
    "WHO":        "https://www.who.int/publications/i/item/9789240058521",
    "KUZNIEWICZ": "https://doi.org/10.1542/peds.2023-065267",
    "EOSCAL":     "https://doi.org/10.1542/peds.2023-065267",
    "2011":       "https://doi.org/10.1542/peds.2011-1572",
    "2019":       "https://doi.org/10.1542/peds.2018-3090",
    "QATAR":      "https://bmjopen.bmj.com/content/13/9/e073216",
}

_CACHE_TTL_HOURS: dict[str, int] = {
    "CRITICAL": 24, "HIGH": 24, "INTERMEDIATE": 12, "LOW": 12,
}


# ── Cache key ─────────────────────────────────────────────────────────────────

def _make_cache_key(risk_payload: dict[str, Any], active_guideline: str) -> str:
    sig = {
        "score":    risk_payload.get("total_score", risk_payload.get("combined_score", 0)),
        "category": risk_payload.get("category", ""),
        "l1":       risk_payload.get("layer1_score", 0),
        "l2":       risk_payload.get("layer2_score", 0),
        "l3":       risk_payload.get("layer3_score", 0),
        "guideline": active_guideline.upper(),
        "drivers":  sorted(
            [d.get("name", "") for d in risk_payload.get("drivers", []) if isinstance(d, dict)]
        ),
    }
    return hashlib.sha256(json.dumps(sig, sort_keys=True).encode()).hexdigest()[:32]


# ── Cache read ────────────────────────────────────────────────────────────────

def _check_cache(cache_key: str) -> ExplanationResponse | None:
    try:
        supabase = get_supabase()
        now = datetime.now(timezone.utc).isoformat()
        rows = (
            supabase.table("llm_explanations")
            .select("*")
            .eq("cache_key", cache_key)
            .or_(f"expires_at.is.null,expires_at.gt.{now}")
            .order("created_at", desc=True)
            .limit(1)
            .execute()
        )
        if not rows.data:
            return None

        row = rows.data[0]
        resp_json = row.get("response_json") or {}
        is_simulated = row.get("is_simulated", False)
        raw_citations = resp_json.get("citation_list", [])
        citations = [
            CitationItem(
                source=c.get("source", ""),
                section=c.get("section", ""),
                chunk_id=c.get("chunk_id", ""),
                similarity_score=float(c.get("similarity_score", 0.0)),
            )
            for c in raw_citations
        ]
        model_ver = row.get("gemini_model_version", "unknown")
        print(f"[LLM] Cache HIT key={cache_key} model={model_ver} simulated={is_simulated}")
        return ExplanationResponse(
            clinical_summary=resp_json.get("clinical_summary", ""),
            per_driver_explanations=resp_json.get("per_driver_explanations", []),
            recommended_actions=resp_json.get("recommended_actions", []),
            evidence_summary=resp_json.get("evidence_summary", ""),
            citation_list=citations,
            confidence_disclaimer=resp_json.get(
                "confidence_disclaimer",
                RULE_BASED_DISCLAIMER if is_simulated else DISCLAIMER,
            ),
            rag_chunks=[],
            model_version=f"cached:{model_ver}",
            fallback_used=is_simulated,
        )
    except Exception as e:
        print(f"[LLM] Cache check failed (non-fatal): {e}")
        return None


# ── Cache write ───────────────────────────────────────────────────────────────

def _write_cache(
    cache_key: str,
    risk_payload: dict[str, Any],
    active_guideline: str,
    result: ExplanationResponse,
    chunks: list[EvidenceChunkResult],
    model_version: str,
    is_simulated: bool,
) -> None:
    try:
        supabase = get_supabase()
        category = str(risk_payload.get("category", ""))
        ttl_h = _CACHE_TTL_HOURS.get(category.upper(), 12)
        expires_at = (datetime.now(timezone.utc) + timedelta(hours=ttl_h)).isoformat()

        citations_json = [
            {"source": c.source, "section": c.section,
             "chunk_id": c.chunk_id, "similarity_score": c.similarity_score}
            for c in chunks
        ]
        response_json = {
            "clinical_summary":        result.clinical_summary,
            "per_driver_explanations": result.per_driver_explanations,
            "recommended_actions":     result.recommended_actions,
            "evidence_summary":        result.evidence_summary,
            "citation_list":           citations_json,
            "confidence_disclaimer":   result.confidence_disclaimer,
        }
        patient = risk_payload.get("patient", {})
        if hasattr(patient, "model_dump"):
            patient = patient.model_dump()

        supabase.table("llm_explanations").insert({
            "cache_key":            cache_key,
            "active_guideline":     active_guideline,
            "is_simulated":         is_simulated,
            "is_cached":            False,
            "gemini_model_version": model_version,
            "rag_chunks_used": [
                {"chunk_id": c.chunk_id, "source": c.source_name,
                 "section": c.section, "score": c.similarity_score}
                for c in chunks
            ],
            "response_json":        response_json,
            "clinical_summary":     result.clinical_summary,
            "risk_analysis":        "",
            "driver_breakdown":     "",
            "recommended_actions":  result.recommended_actions,
            "antibiotic_plan":      {},
            "monitoring_plan":      "",
            "escalation_criteria":  "",
            "guideline_citations":  [],
            "patient_snapshot":     patient,
            "eoscal_score":         risk_payload.get("total_score", risk_payload.get("combined_score")),
            "risk_category":        category,
            "expires_at":           expires_at,
        }).execute()
        print(f"[LLM] Cached key={cache_key} ttl={ttl_h}h model={model_version} simulated={is_simulated}")
    except Exception as e:
        print(f"[LLM] Cache write failed (non-fatal): {e}")


def _log_rag_query(
    query: str,
    active_guideline: str,
    chunks: list[EvidenceChunkResult],
    method: str = "hybrid",
) -> None:
    try:
        supabase = get_supabase()
        supabase.table("rag_query_log").insert({
            "query_text":       query[:500],
            "active_guideline": active_guideline,
            "chunks_returned": [
                {"chunk_id": c.chunk_id, "source": c.source_name,
                 "section": c.section, "score": c.similarity_score}
                for c in chunks
            ],
            "chunk_count":      len(chunks),
            "retrieval_method": method,
        }).execute()
    except Exception:
        pass


# ── Shared prompt builder ─────────────────────────────────────────────────────

def _build_prompt(
    risk_payload: dict[str, Any],
    active_guideline: str,
    chunks: list[EvidenceChunkResult],
) -> str:
    chunk_text = "\n\n".join(
        f"[{c.chunk_id}] {c.source_name} — {c.section}:\n{c.chunk_text}"
        for c in chunks
    )
    patient = risk_payload.get("patient", {})
    if hasattr(patient, "model_dump"):
        patient = patient.model_dump()
    valid_ids = [c.chunk_id for c in chunks]

    return f"""You are NeoGuard AI, a clinical explanation engine. Your only role is to explain \
decisions already made by the deterministic EOSCAL rule engine. You do NOT recalculate risk scores \
or make independent clinical decisions.

ACTIVE GUIDELINE: {active_guideline}

DE-IDENTIFIED PATIENT DATA (no PHI):
- Gestational age (weeks): {patient.get('gestational_age_weeks', 'unknown')}
- Maternal temperature: {patient.get('maternal_temperature', 'unknown')} °C
- ROM hours: {patient.get('rom_hours', 'unknown')}
- GBS positive: {patient.get('gbs_positive', 'unknown')}
- Respiratory distress: {patient.get('respiratory_distress', 'unknown')}
- CRP: {patient.get('crp_level', 'unknown')} mg/L
- Blood culture positive: {patient.get('blood_culture_positive', 'unknown')}

RISK RESULT (already calculated — do NOT recalculate):
- Category: {risk_payload.get('category', risk_payload.get('risk_category'))}
- Combined score: {risk_payload.get('total_score', risk_payload.get('combined_score'))}
- Layer scores: L1={risk_payload.get('layer1_score')}, L2={risk_payload.get('layer2_score')}, L3={risk_payload.get('layer3_score')}
- Probability per 1000 births: {risk_payload.get('probability_per_1000', 'N/A')}
- Risk drivers: {json.dumps(risk_payload.get('drivers', []))}

RETRIEVED GUIDELINE EVIDENCE (valid chunk IDs: {json.dumps(valid_ids)}):
{chunk_text}

INSTRUCTIONS:
1. Write a clinical_summary of 2-3 sentences explaining why this patient received their risk category.
2. For each driver in the risk drivers list, write a per_driver_explanation citing the relevant guideline chunk.
3. List recommended_actions as numbered steps, strictly following {active_guideline} guidance from the chunks.
4. Write an evidence_summary of 1-2 sentences synthesising the retrieved evidence.
5. Populate citation_list using ONLY the chunk IDs from the valid list above — never invent IDs.
6. Every factual claim must trace to a retrieved chunk. Do not add clinical facts not present in the chunks.

Respond with ONLY valid JSON — no markdown fences, no preamble, no trailing text.
Schema:
{{
  "clinical_summary": "<string>",
  "per_driver_explanations": [
    {{"factor": "<driver name>", "explanation": "<1-2 sentences citing guideline chunk>"}}
  ],
  "recommended_actions": ["<action 1>", "<action 2>"],
  "evidence_summary": "<string>",
  "citation_list": [
    {{"source": "<source_name>", "section": "<section>", "chunk_id": "<id from valid list>", "similarity_score": <float>}}
  ],
  "confidence_disclaimer": "{DISCLAIMER}"
}}"""


# ── Parse LLM JSON response ───────────────────────────────────────────────────

def _parse_llm_response(
    raw: str,
    chunks: list[EvidenceChunkResult],
    model_version: str,
    chunk_responses: list[EvidenceChunkResponse],
) -> ExplanationResponse:
    """Parse JSON from any LLM response. Raises on failure."""
    # Strip markdown fences
    text = raw.strip()
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.rsplit("```", 1)[0].strip()

    data = json.loads(text)  # raises json.JSONDecodeError on failure

    valid_ids = {c.chunk_id for c in chunks}
    citations: list[CitationItem] = []
    for c in data.get("citation_list", []):
        cid = c.get("chunk_id", "")
        if cid and cid not in valid_ids:
            continue  # drop hallucinated IDs
        citations.append(CitationItem(
            source=c.get("source", ""),
            section=c.get("section", ""),
            chunk_id=cid,
            similarity_score=float(c.get("similarity_score", 0.0)),
        ))

    if not citations:
        citations = [
            CitationItem(
                source=c.source_name, section=c.section,
                chunk_id=c.chunk_id, similarity_score=c.similarity_score,
            )
            for c in chunks
        ]

    return ExplanationResponse(
        clinical_summary=data.get("clinical_summary", ""),
        per_driver_explanations=data.get("per_driver_explanations", []),
        recommended_actions=data.get("recommended_actions", []),
        evidence_summary=data.get("evidence_summary", ""),
        citation_list=citations,
        confidence_disclaimer=data.get("confidence_disclaimer", DISCLAIMER),
        rag_chunks=chunk_responses,
        model_version=model_version,
        fallback_used=False,
    )


# ── Gemini call ───────────────────────────────────────────────────────────────

def _call_gemini(
    prompt: str,
    settings,
) -> str:
    """Call Gemini and return raw text. Raises on any error."""
    genai.configure(api_key=settings.gemini_api_key)
    model = genai.GenerativeModel(
        model_name=settings.gemini_model,
        generation_config={
            "response_mime_type": "application/json",
            "temperature": 0.1,
            "top_p": 0.9,
            "max_output_tokens": 2048,
        },
    )
    print(f"[Gemini] Calling model={settings.gemini_model}")
    response = model.generate_content(prompt)
    return response.text


# ── Groq call ─────────────────────────────────────────────────────────────────

def _call_groq(
    prompt: str,
    settings,
) -> str:
    """Call Groq (Llama 3.3 70B) and return raw text. Raises on any error."""
    client = Groq(api_key=settings.groq_api_key)
    print(f"[Groq] Calling model={settings.groq_model}")
    response = client.chat.completions.create(
        model=settings.groq_model,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are NeoGuard AI, a neonatal clinical decision support engine. "
                    "You always respond with valid JSON only — no markdown, no preamble."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        temperature=0.1,
        max_tokens=2048,
        # Groq supports JSON mode on Llama models
        response_format={"type": "json_object"},
    )
    return response.choices[0].message.content


# ── Rule-based fallback ───────────────────────────────────────────────────────

def _fallback_explanation(
    risk_payload: dict[str, Any],
    active_guideline: str,
    chunks: list[EvidenceChunkResult],
) -> ExplanationResponse:
    """Deterministic rule-based summary. Explicitly NOT AI-generated."""
    category = str(risk_payload.get("category", risk_payload.get("risk_category", "INTERMEDIATE")))
    score = risk_payload.get("total_score", risk_payload.get("combined_score", 0))

    actions_map = {
        "LOW": [
            "Routine observation per unit protocol.",
            "Monitor vital signs every 12 hours for the first 24 hours.",
            "Reassess if any clinical signs develop.",
        ],
        "INTERMEDIATE": [
            "Enhanced monitoring every 4 hours.",
            "Obtain blood culture and CRP at 18–24 hours.",
            "Senior clinician review if clinical status deteriorates.",
            "Review antibiotic decision at 36 hours based on culture and CRP.",
        ],
        "HIGH": [
            "Obtain blood culture before antibiotics — do not delay treatment.",
            "Initiate empirical IV antibiotics within 1 hour per active guideline.",
            "Senior neonatologist review within 1 hour.",
            "Repeat CRP at 18–24 hours; review blood culture at 36–48 hours.",
        ],
        "CRITICAL": [
            "Immediate IV antibiotics — do not wait for culture results.",
            "NICU admission and full sepsis workup.",
            "Supportive care: perfusion, ventilation, thermal management.",
            "Senior neonatologist within 30 minutes.",
            "Urgent FBC, CRP, blood gas, and blood culture.",
        ],
    }

    category_key = category.upper().replace(" ", "_")
    actions = actions_map.get("INTERMEDIATE", [])
    for key, value in actions_map.items():
        if key in category_key:
            actions = value
            break

    citations = [
        CitationItem(source=c.source_name, section=c.section,
                     chunk_id=c.chunk_id, similarity_score=c.similarity_score)
        for c in chunks
    ]
    drivers_text = ", ".join(
        d.get("name", "") for d in risk_payload.get("drivers", []) if isinstance(d, dict)
    ) or "none identified"

    return ExplanationResponse(
        clinical_summary=(
            f"Rule-based summary (no AI): This infant has {category} EOS risk "
            f"(score {score}) based on the EOSCAL three-layer assessment. "
            f"Active risk drivers: {drivers_text}. "
            f"Recommendations follow {active_guideline} protocol."
        ),
        per_driver_explanations=[
            {"factor": d.get("name", "Unknown"), "explanation": d.get("reason", "Contributed to risk score.")}
            for d in risk_payload.get("drivers", [])[:6]
            if isinstance(d, dict)
        ],
        recommended_actions=actions,
        evidence_summary=chunks[0].chunk_text[:200] + "…" if chunks else "No guideline chunks retrieved.",
        citation_list=citations,
        confidence_disclaimer=RULE_BASED_DISCLAIMER,
        rag_chunks=[EvidenceChunkResponse(**c.to_dict()) for c in chunks],
        model_version="rule-based-fallback",
        fallback_used=True,
    )


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_explanation(
    risk_payload: dict[str, Any],
    active_guideline: str,
    chunks: list[EvidenceChunkResult],
    query: str = "",
) -> ExplanationResponse:
    settings = get_settings()
    chunk_responses = [EvidenceChunkResponse(**c.to_dict()) for c in chunks]
    cache_key = _make_cache_key(risk_payload, active_guideline)

    # ── 1. Cache ──────────────────────────────────────────────────────────────
    cached = _check_cache(cache_key)
    if cached is not None:
        cached.rag_chunks = chunk_responses
        _log_rag_query(query or "cached", active_guideline, chunks, method="cache")
        return cached

    # ── 2. Log RAG query ──────────────────────────────────────────────────────
    _log_rag_query(
        query or _build_query_string(risk_payload, active_guideline),
        active_guideline, chunks,
        method="hybrid" if chunks else "seed",
    )

    prompt = _build_prompt(risk_payload, active_guideline, chunks)

    # ── 3. Try Gemini ─────────────────────────────────────────────────────────
    if settings.gemini_api_key:
        try:
            raw = _call_gemini(prompt, settings)
            result = _parse_llm_response(raw, chunks, settings.gemini_model, chunk_responses)
            _write_cache(cache_key, risk_payload, active_guideline, result,
                         chunks, settings.gemini_model, is_simulated=False)
            print(f"[Gemini] Success")
            return result
        except Exception as e:
            print(f"[Gemini] Failed ({type(e).__name__}: {e}) — trying Groq fallback")
    else:
        print("[LLM] No GEMINI_API_KEY — skipping Gemini, trying Groq")

    # ── 4. Try Groq (Llama 3.3 70B) ──────────────────────────────────────────
    if settings.groq_api_key:
        try:
            raw = _call_groq(prompt, settings)
            result = _parse_llm_response(raw, chunks, settings.groq_model, chunk_responses)
            _write_cache(cache_key, risk_payload, active_guideline, result,
                         chunks, settings.groq_model, is_simulated=False)
            print(f"[Groq] Success")
            return result
        except Exception as e:
            print(f"[Groq] Failed ({type(e).__name__}: {e}) — falling back to rule-based")
    else:
        print("[LLM] No GROQ_API_KEY — skipping Groq")

    # ── 5. Rule-based final fallback ──────────────────────────────────────────
    print("[LLM] Both Gemini and Groq unavailable — using rule-based fallback")
    result = _fallback_explanation(risk_payload, active_guideline, chunks)
    result.rag_chunks = chunk_responses
    _write_cache(cache_key, risk_payload, active_guideline, result,
                 chunks, "rule-based-fallback", is_simulated=True)
    return result


def _build_query_string(risk_payload: dict[str, Any], guideline: str) -> str:
    parts = [f"EOS {guideline} neonatal sepsis", str(risk_payload.get("category", ""))]
    for d in risk_payload.get("drivers", []):
        if isinstance(d, dict) and d.get("name"):
            parts.append(str(d["name"]))
    return " ".join(parts)[:300]


# ── Evidence overview (for /api/v1/evidence/overview) ─────────────────────────

def generate_evidence_overview(
    query: str,
    active_guideline: str,
    chunks: list[dict],
) -> tuple[str, bool]:
    """
    Returns (overview_text, generated_by_ai).
    Tries Gemini first, falls back to Groq, returns ('', False) if both fail.
    """
    if not chunks:
        return "", False

    settings = get_settings()
    chunk_context = "\n\n".join(
        f"[{c.get('source', '')} — {c.get('section', '')}]: "
        f"{c.get('chunk_text', c.get('content', ''))[:500]}"
        for c in chunks
    )
    prompt = (
        f'You are a neonatal sepsis clinical decision support assistant.\n'
        f'A clinician searched for: "{query}"\n'
        f'Active guideline: {active_guideline}\n\n'
        f'RETRIEVED GUIDELINE EVIDENCE:\n{chunk_context}\n\n'
        f'Write a concise 3-4 sentence clinical overview that directly answers the query, '
        f'synthesising the evidence above. Be specific, cite sources by name (e.g. NICE NG195, '
        f'AAP 2023). Use clinical language. Do not add information not in the chunks. '
        f'Output plain text only — no markdown, no headers, no bullets.'
    )

    # Try Gemini
    if settings.gemini_api_key:
        try:
            genai.configure(api_key=settings.gemini_api_key)
            model = genai.GenerativeModel(
                model_name=settings.gemini_model,
                generation_config={"temperature": 0.1, "max_output_tokens": 512},
            )
            response = model.generate_content(prompt)
            text = (response.text or "").strip()
            if text:
                print(f"[Gemini] Evidence overview OK")
                return text, True
        except Exception as e:
            print(f"[Gemini] Evidence overview failed ({type(e).__name__}) — trying Groq")

    # Try Groq
    if settings.groq_api_key:
        try:
            client = Groq(api_key=settings.groq_api_key)
            response = client.chat.completions.create(
                model=settings.groq_model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1,
                max_tokens=512,
            )
            text = (response.choices[0].message.content or "").strip()
            if text:
                print(f"[Groq] Evidence overview OK")
                return text, True
        except Exception as e:
            print(f"[Groq] Evidence overview failed ({type(e).__name__})")

    return "", False


# ── Evidence cards (for /api/v1/evidence/cards) ───────────────────────────────

def generate_evidence_cards(
    query: str,
    active_guideline: str,
    chunks: list[dict],
) -> tuple[list[dict], bool]:
    """
    Returns (cards_list, generated_by_ai).
    Tries Gemini first, falls back to Groq, returns ([], False) if both fail.
    """
    if not chunks:
        return [], False

    settings = get_settings()
    chunk_list_json = json.dumps([
        {
            "index": i,
            "source": c.get("source", c.get("source_name", "")),
            "section": c.get("section", ""),
            "content": c.get("chunk_text", c.get("content", ""))[:600],
        }
        for i, c in enumerate(chunks)
    ])

    prompt = (
        f'You are a neonatal sepsis clinical decision support assistant.\n'
        f'Clinician query: "{query}"\n'
        f'Active guideline: {active_guideline}\n\n'
        f'GUIDELINE CHUNKS:\n{chunk_list_json}\n\n'
        f'For EACH chunk produce a JSON object:\n'
        f'- "index": integer matching the chunk index\n'
        f'- "headline": one sentence (max 15 words) directly answering the query from this chunk\n'
        f'- "processed_answer": 2-3 sentences explaining this chunk for the query in clinical language\n'
        f'- "exact_excerpt": copy the single most relevant sentence verbatim from the chunk content\n\n'
        f'Respond ONLY with a valid JSON array of objects. No markdown, no preamble.'
    )

    def _try_parse_cards(raw: str) -> list[dict]:
        text = raw.strip()
        if text.startswith("```"):
            text = text.split("```", 2)[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.rsplit("```", 1)[0].strip()
        # Groq json_object mode may wrap array in {"cards": [...]}
        parsed = json.loads(text)
        if isinstance(parsed, list):
            return parsed
        # unwrap common wrapper keys
        for key in ("cards", "results", "data", "items"):
            if key in parsed and isinstance(parsed[key], list):
                return parsed[key]
        return []

    # Try Gemini
    if settings.gemini_api_key:
        try:
            genai.configure(api_key=settings.gemini_api_key)
            model = genai.GenerativeModel(
                model_name=settings.gemini_model,
                generation_config={
                    "response_mime_type": "application/json",
                    "temperature": 0.1,
                    "max_output_tokens": 2048,
                },
            )
            response = model.generate_content(prompt)
            cards = _try_parse_cards(response.text or "")
            if cards:
                print(f"[Gemini] Evidence cards OK ({len(cards)} cards)")
                return cards, True
        except Exception as e:
            print(f"[Gemini] Evidence cards failed ({type(e).__name__}) — trying Groq")

    # Try Groq
    if settings.groq_api_key:
        try:
            client = Groq(api_key=settings.groq_api_key)
            response = client.chat.completions.create(
                model=settings.groq_model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a clinical AI assistant. Respond only with valid JSON.",
                    },
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1,
                max_tokens=2048,
                response_format={"type": "json_object"},
            )
            cards = _try_parse_cards(response.choices[0].message.content or "")
            if cards:
                print(f"[Groq] Evidence cards OK ({len(cards)} cards)")
                return cards, True
        except Exception as e:
            print(f"[Groq] Evidence cards failed ({type(e).__name__})")

    return [], False