"""Gemini 2.0 Flash clinical explanation engine (Section 8)."""

from __future__ import annotations

import json
import traceback
from typing import Any

import google.generativeai as genai

from config import get_settings
from rag.retrieve import EvidenceChunkResult
from schemas import CitationItem, EvidenceChunkResponse, ExplanationResponse


DISCLAIMER = (
    "This explanation is generated by AI and is provided for educational support only. "
    "Clinical decisions must be made by a qualified clinician based on the full clinical picture. "
    "NeoGuard AI does not replace clinical judgement."
)


def _build_prompt(
    risk_payload: dict[str, Any],
    active_guideline: str,
    chunks: list[EvidenceChunkResult],
) -> str:
    chunk_text = "\n\n".join(
        f"[{c.chunk_id}] {c.source_name} — {c.section}:\n{c.chunk_text}"
        for c in chunks
    )

    patient = risk_payload.get("patient", {})
    if hasattr(patient, "model_dump"):
        patient = patient.model_dump()

    return f"""You are NeoGuard AI clinical explanation engine. You EXPLAIN decisions already made by the deterministic EOSCAL rule engine. You do NOT change the risk score or make independent clinical decisions.

ACTIVE GUIDELINE: {active_guideline}

DE-IDENTIFIED CLINICAL DATA (no PHI):
- Gestational age (weeks): {patient.get('gestational_age_weeks', 'unknown')}
- Maternal temperature: {patient.get('maternal_temperature', 'unknown')}°C
- ROM hours: {patient.get('rom_hours', 'unknown')}
- GBS positive: {patient.get('gbs_positive', 'unknown')}
- Respiratory distress: {patient.get('respiratory_distress', 'unknown')}
- CRP: {patient.get('crp_level', 'unknown')} mg/L
- Blood culture positive: {patient.get('blood_culture_positive', 'unknown')}

RISK RESULT (already calculated — do not recalculate):
- Category: {risk_payload.get('category', risk_payload.get('risk_category'))}
- Combined score: {risk_payload.get('total_score', risk_payload.get('combined_score'))}
- Layer scores: L1={risk_payload.get('layer1_score')}, L2={risk_payload.get('layer2_score')}, L3={risk_payload.get('layer3_score')}
- Probability per 1000 births: {risk_payload.get('probability_per_1000', 'N/A')}
- Drivers: {json.dumps(risk_payload.get('drivers', []))}

RETRIEVED GUIDELINE EVIDENCE (cite these by chunk_id):
{chunk_text}

Respond with ONLY valid JSON matching this schema:
{{
  "clinical_summary": "2-3 sentences",
  "per_driver_explanations": [{{"factor": "name", "explanation": "significance + guideline basis"}}],
  "recommended_actions": ["numbered action strings aligned to {active_guideline}"],
  "evidence_summary": "1-2 sentences synthesizing evidence",
  "citation_list": [{{"source": "name", "section": "section", "chunk_id": "id", "similarity_score": 0.0}}],
  "confidence_disclaimer": "{DISCLAIMER}"
}}
Every sentence must trace to a retrieved guideline chunk. Use chunk_id in citations."""


def _fallback_explanation(
    risk_payload: dict[str, Any],
    active_guideline: str,
    chunks: list[EvidenceChunkResult],
) -> ExplanationResponse:
    """Deterministic rule-based fallback when Gemini unavailable."""
    category = str(risk_payload.get("category", risk_payload.get("risk_category", "INTERMEDIATE")))
    score = risk_payload.get("total_score", risk_payload.get("combined_score", 0))

    actions_map = {
        "LOW": ["Routine observation", "Monitor vital signs per unit protocol"],
        "INTERMEDIATE": [
            "Enhanced monitoring every 4 hours",
            "Consider baseline blood culture and CRP",
            "Senior review if clinical deterioration",
        ],
        "HIGH": [
            "Blood culture before antibiotics if possible",
            "Empirical IV antibiotics per active guideline",
            "Senior neonatologist review",
        ],
        "CRITICAL": [
            "Immediate IV antibiotics — do not delay for cultures",
            "NICU admission and full sepsis workup",
            "Supportive care for perfusion and ventilation",
        ],
    }

    category_key = category.upper().replace(" ", "_")
    for key in actions_map:
        if key in category_key:
            actions = actions_map[key]
            break
    else:
        actions = actions_map["INTERMEDIATE"]

    citations = [
        CitationItem(
            source=c.source_name,
            section=c.section,
            chunk_id=c.chunk_id,
            similarity_score=c.similarity_score,
        )
        for c in chunks
    ]

    return ExplanationResponse(
        clinical_summary=(
            f"This infant has {category} EOS risk (score {score}/32) based on the three-layer EOSCAL assessment. "
            f"Recommendations follow {active_guideline} guidance and retrieved evidence."
        ),
        per_driver_explanations=[
            {
                "factor": d.get("name", "Unknown"),
                "explanation": d.get("reason", "Contributed to risk score."),
            }
            for d in risk_payload.get("drivers", [])[:6]
        ],
        recommended_actions=actions,
        evidence_summary=(
            chunks[0].chunk_text[:200] + "..." if chunks else "No guideline chunks retrieved."
        ),
        citation_list=citations,
        confidence_disclaimer=DISCLAIMER,
        rag_chunks=[EvidenceChunkResponse(**c.to_dict()) for c in chunks],
        model_version="rule-based-fallback",
        fallback_used=True,
    )


def generate_explanation(
    risk_payload: dict[str, Any],
    active_guideline: str,
    chunks: list[EvidenceChunkResult],
) -> ExplanationResponse:
    settings = get_settings()

    chunk_responses = [EvidenceChunkResponse(**c.to_dict()) for c in chunks]

    if not settings.gemini_api_key:
        result = _fallback_explanation(risk_payload, active_guideline, chunks)
        result.rag_chunks = chunk_responses
        return result

    try:
        genai.configure(api_key=settings.gemini_api_key)
        model = genai.GenerativeModel(
            model_name=settings.gemini_model,
            generation_config={
                "response_mime_type": "application/json",
                "temperature": 0.2,
            },
        )
        prompt = _build_prompt(risk_payload, active_guideline, chunks)
        response = model.generate_content(prompt)
        data = json.loads(response.text)

        citations = [
            CitationItem(**c) for c in data.get("citation_list", [])
        ]
        if not citations:
            citations = [
                CitationItem(
                    source=c.source_name,
                    section=c.section,
                    chunk_id=c.chunk_id,
                    similarity_score=c.similarity_score,
                )
                for c in chunks
            ]

        return ExplanationResponse(
            clinical_summary=data.get("clinical_summary", ""),
            per_driver_explanations=data.get("per_driver_explanations", []),
            recommended_actions=data.get("recommended_actions", []),
            evidence_summary=data.get("evidence_summary", ""),
            citation_list=citations,
            confidence_disclaimer=data.get("confidence_disclaimer", DISCLAIMER),
            rag_chunks=chunk_responses,
            model_version=settings.gemini_model,
        )
    except Exception:
        print(f"[Gemini] api_key_set={bool(settings.gemini_api_key)} model={settings.gemini_model}")
        result = _fallback_explanation(risk_payload, active_guideline, chunks)
        print(f"[Gemini ERROR] {type(e).__name__}: {e}")
        traceback.print_exc()
        result.rag_chunks = chunk_responses
        return result
